/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demogradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class WelcomeTest {
    @Test public void testSomeLibraryMethod() {
        Welcome classUnderTest = new Welcome();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
